"""empty message

Revision ID: 0b76c78086be
Revises: 
Create Date: 2021-11-19 17:31:45.346645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b76c78086be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('heigth', sa.DECIMAL(), nullable=False),
    sa.Column('mass', sa.DECIMAL(), nullable=False),
    sa.Column('hairColor', sa.String(length=250), nullable=False),
    sa.Column('eyeColor', sa.String(length=250), nullable=False),
    sa.Column('homeworld', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['people_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('people_details')
    # ### end Alembic commands ###
