"""empty message

Revision ID: 17f2d7b1ee4f
Revises: 2c0a574693ff
Create Date: 2021-11-16 10:24:15.548598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17f2d7b1ee4f'
down_revision = '2c0a574693ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('gravity', sa.String(length=80), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.String(length=80), nullable=False),
    sa.Column('orbitalperiod', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('planet', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'planet', 'planet_details', ['planet_id'], ['id'])
    op.drop_column('planet', 'terrain')
    op.drop_column('planet', 'orbitalperiod')
    op.drop_column('planet', 'climate')
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'gravity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('gravity', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('planet', sa.Column('diameter', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('planet', sa.Column('climate', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planet', sa.Column('orbitalperiod', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('planet', sa.Column('terrain', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'planet_id')
    op.drop_table('planet_details')
    # ### end Alembic commands ###
